apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-zaoe
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oeya-tenant/rhtap-demo-app/hacbs-test-project-zaoe@sha256:d5d32a23a4f26f97b895260f7040a030268c6208b26ba0f5dc09371201867f6c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
